<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Collin Real (yhi267)">

<title>Exercise 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Real_Collin_Exercise4_files/libs/clipboard/clipboard.min.js"></script>
<script src="Real_Collin_Exercise4_files/libs/quarto-html/quarto.js"></script>
<script src="Real_Collin_Exercise4_files/libs/quarto-html/popper.min.js"></script>
<script src="Real_Collin_Exercise4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Real_Collin_Exercise4_files/libs/quarto-html/anchor.min.js"></script>
<link href="Real_Collin_Exercise4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Real_Collin_Exercise4_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Real_Collin_Exercise4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Real_Collin_Exercise4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Real_Collin_Exercise4_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercise 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Collin Real (yhi267) </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="import-libraries" class="level2">
<h2 class="anchored" data-anchor-id="import-libraries">Import Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlbench)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(earth)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generate-trainingtest-datasets-visualize-and-pre-process-data" class="level2">
<h2 class="anchored" data-anchor-id="generate-trainingtest-datasets-visualize-and-pre-process-data">Generate training/test datasets, visualize and pre-process data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Training Data</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>training_data <span class="ot">&lt;-</span> <span class="fu">mlbench.friedman1</span>(<span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>training_data<span class="sc">$</span>x <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(training_data<span class="sc">$</span>x)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">featurePlot</span>(training_data<span class="sc">$</span>x, training_data<span class="sc">$</span>y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Real_Collin_Exercise4_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test Data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">mlbench.friedman1</span>(<span class="dv">5000</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>test_data<span class="sc">$</span>x <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(test_data<span class="sc">$</span>x)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Center and Scale Data</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>pre_process_data <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(training_data<span class="sc">$</span>x, <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>train_transformed <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_process_data, training_data<span class="sc">$</span>x)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>test_transformed <span class="ot">&lt;-</span> <span class="fu">predict</span>(pre_process_data, test_data<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="k-nearest-neighbors-knn" class="level2">
<h2 class="anchored" data-anchor-id="k-nearest-neighbors-knn">k-Nearest Neighbors (kNN):</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>knn_model <span class="ot">&lt;-</span> <span class="fu">train</span>(training_data<span class="sc">$</span>x,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                  training_data<span class="sc">$</span>y,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"knn"</span>, </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProc =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>), </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>knn_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(knn_model, <span class="at">newdata =</span> test_data<span class="sc">$</span>x)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>knn_results <span class="ot">&lt;-</span> <span class="fu">postResample</span>(<span class="at">pred =</span> knn_predictions, <span class="at">obs =</span> test_data<span class="sc">$</span>y)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>knn_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>k-Nearest Neighbors 

200 samples
 10 predictor

Pre-processing: centered (10), scaled (10) 
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 200, 200, 200, 200, 200, 200, ... 
Resampling results across tuning parameters:

  k   RMSE      Rsquared   MAE     
   5  3.654912  0.4779838  2.958475
   7  3.529432  0.5118581  2.861742
   9  3.446330  0.5425096  2.780756
  11  3.378049  0.5723793  2.719410
  13  3.332339  0.5953773  2.692863
  15  3.309235  0.6111389  2.663046
  17  3.317408  0.6201421  2.678898
  19  3.311667  0.6333800  2.682098
  21  3.316340  0.6407537  2.688887
  23  3.326040  0.6491480  2.705915

RMSE was used to select the optimal model using the smallest value.
The final value used for the model was k = 15.</code></pre>
</div>
</div>
</section>
<section id="multivariate-adaptive-regression-splines-mars" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-adaptive-regression-splines-mars">Multivariate Adaptive Regression Splines (MARS):</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mars_model <span class="ot">&lt;-</span> <span class="fu">train</span>(training_data<span class="sc">$</span>x,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                   training_data<span class="sc">$</span>y,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"earth"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">preProc =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>mars_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(mars_model, <span class="at">newdata =</span> test_data<span class="sc">$</span>x)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>mars_results <span class="ot">&lt;-</span> <span class="fu">postResample</span>(<span class="at">pred =</span> mars_predictions, <span class="at">obs =</span> test_data<span class="sc">$</span>y)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>mars_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Multivariate Adaptive Regression Spline 

200 samples
 10 predictor

Pre-processing: centered (10), scaled (10) 
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 200, 200, 200, 200, 200, 200, ... 
Resampling results across tuning parameters:

  nprune  RMSE      Rsquared   MAE     
   2      4.447045  0.2249607  3.650128
   3      3.744821  0.4546610  3.019175
   4      2.828643  0.6892908  2.244131
   6      2.406670  0.7747079  1.906733
   7      2.027113  0.8375721  1.594956
   9      1.800794  0.8728377  1.411703
  10      1.810047  0.8721377  1.412023
  12      1.831608  0.8700790  1.430044
  13      1.839717  0.8686550  1.440537
  15      1.856211  0.8663787  1.452430

Tuning parameter 'degree' was held constant at a value of 1
RMSE was used to select the optimal model using the smallest value.
The final values used for the model were nprune = 9 and degree = 1.</code></pre>
</div>
</div>
</section>
<section id="neural-network" class="level2">
<h2 class="anchored" data-anchor-id="neural-network">Neural Network</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>neural_network_model <span class="ot">&lt;-</span> <span class="fu">train</span>(training_data<span class="sc">$</span>x,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                   training_data<span class="sc">$</span>y,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"nnet"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">preProc =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tuneLength =</span> <span class="dv">10</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trace =</span> <span class="cn">FALSE</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">maxit =</span> <span class="dv">1000</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>neural_network_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(neural_network_model, <span class="at">newdata =</span> test_data<span class="sc">$</span>x)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>neural_network_results <span class="ot">&lt;-</span> <span class="fu">postResample</span>(<span class="at">pred =</span> neural_network_predictions, <span class="at">obs =</span> test_data<span class="sc">$</span>y)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>neural_network_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neural Network 

200 samples
 10 predictor

Pre-processing: centered (10), scaled (10) 
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 200, 200, 200, 200, 200, 200, ... 
Resampling results across tuning parameters:

  size  decay         RMSE      Rsquared    MAE     
   1    0.0000000000  14.47801         NaN  13.59034
   1    0.0001000000  14.47801  0.46388412  13.59034
   1    0.0002371374  14.47802  0.54494073  13.59034
   1    0.0005623413  14.47802  0.61944972  13.59034
   1    0.0013335214  14.47802  0.09093040  13.59035
   1    0.0031622777  14.47802  0.30228015  13.59035
   1    0.0074989421  14.47803  0.56808124  13.59036
   1    0.0177827941  14.47805  0.71039904  13.59038
   1    0.0421696503  14.47809  0.73040205  13.59043
   1    0.1000000000  14.47818  0.73494609  13.59053
   3    0.0000000000  14.47801         NaN  13.59034
   3    0.0001000000  14.47801  0.34800441  13.59034
   3    0.0002371374  14.47802  0.45676945  13.59034
   3    0.0005623413  14.47802  0.43051350  13.59034
   3    0.0013335214  14.47802  0.17944723  13.59034
   3    0.0031622777  14.47802  0.34885263  13.59035
   3    0.0074989421  14.47802  0.66340789  13.59035
   3    0.0177827941  14.47804  0.71716435  13.59037
   3    0.0421696503  14.47807  0.71146831  13.59040
   3    0.1000000000  14.47813  0.73501063  13.59047
   5    0.0000000000  14.47801         NaN  13.59034
   5    0.0001000000  14.47801  0.34108207  13.59034
   5    0.0002371374  14.47801  0.43036960  13.59034
   5    0.0005623413  14.47802  0.21949661  13.59034
   5    0.0013335214  14.47802  0.16071675  13.59034
   5    0.0031622777  14.47802  0.39392125  13.59034
   5    0.0074989421  14.47802  0.62726936  13.59035
   5    0.0177827941  14.47803  0.71623817  13.59036
   5    0.0421696503  14.47805  0.73402288  13.59039
   5    0.1000000000  14.47810  0.73466004  13.59044
   7    0.0000000000  14.47801         NaN  13.59034
   7    0.0001000000  14.47801  0.23898081  13.59034
   7    0.0002371374  14.47801  0.35110213  13.59034
   7    0.0005623413  14.47802  0.23402091  13.59034
   7    0.0013335214  14.47802  0.12715521  13.59034
   7    0.0031622777  14.47802  0.39694516  13.59034
   7    0.0074989421  14.47802  0.60175109  13.59035
   7    0.0177827941  14.47803  0.70582638  13.59036
   7    0.0421696503  14.47805  0.72921800  13.59038
   7    0.1000000000  14.47809  0.73543577  13.59043
   9    0.0000000000  14.47801         NaN  13.59034
   9    0.0001000000  14.47801  0.14616290  13.59034
   9    0.0002371374  14.47801  0.18887281  13.59034
   9    0.0005623413  14.47802  0.13174456  13.59034
   9    0.0013335214  14.47802  0.12235462  13.59034
   9    0.0031622777  14.47802  0.34661430  13.59034
   9    0.0074989421  14.47802  0.61749255  13.59035
   9    0.0177827941  14.47803  0.68744029  13.59036
   9    0.0421696503  14.47805  0.72754367  13.59038
   9    0.1000000000  14.47808  0.73665992  13.59042
  11    0.0000000000  14.47801         NaN  13.59034
  11    0.0001000000  14.47801  0.08908443  13.59034
  11    0.0002371374  14.47801  0.28164363  13.59034
  11    0.0005623413  14.47801  0.05349839  13.59034
  11    0.0013335214  14.47802  0.10594059  13.59034
  11    0.0031622777  14.47802  0.31727910  13.59034
  11    0.0074989421  14.47802  0.63361111  13.59035
  11    0.0177827941  14.47803  0.69885458  13.59035
  11    0.0421696503  14.47804  0.72941521  13.59037
  11    0.1000000000  14.47808  0.73750572  13.59041
  13    0.0000000000  14.47801         NaN  13.59034
  13    0.0001000000  14.47801  0.19210023  13.59034
  13    0.0002371374  14.47802  0.11206074  13.59034
  13    0.0005623413  14.47801  0.09392261  13.59034
  13    0.0013335214  14.47802  0.13329265  13.59034
  13    0.0031622777  14.47802  0.41331057  13.59034
  13    0.0074989421  14.47802  0.63739490  13.59035
  13    0.0177827941  14.47803  0.69752049  13.59035
  13    0.0421696503  14.47804  0.73035630  13.59037
  13    0.1000000000  14.47807  0.73589138  13.59041
  15    0.0000000000  14.47801         NaN  13.59034
  15    0.0001000000  14.47801  0.13752235  13.59034
  15    0.0002371374  14.47802  0.05144031  13.59034
  15    0.0005623413  14.47801  0.12997206  13.59034
  15    0.0013335214  14.47802  0.12810176  13.59034
  15    0.0031622777  14.47802  0.40560042  13.59034
  15    0.0074989421  14.47802  0.62308752  13.59035
  15    0.0177827941  14.47803  0.69911203  13.59035
  15    0.0421696503  14.47804  0.73074432  13.59037
  15    0.1000000000  14.47807  0.73527103  13.59040
  17    0.0000000000  14.47801         NaN  13.59034
  17    0.0001000000  14.47801  0.13660237  13.59034
  17    0.0002371374  14.47801  0.08365132  13.59034
  17    0.0005623413  14.47801  0.10863086  13.59034
  17    0.0013335214  14.47802  0.10883388  13.59034
  17    0.0031622777  14.47802  0.38999051  13.59034
  17    0.0074989421  14.47802  0.58645670  13.59035
  17    0.0177827941  14.47802  0.69878013  13.59035
  17    0.0421696503  14.47804  0.72499187  13.59037
  17    0.1000000000  14.47807  0.73501430  13.59040
  19    0.0000000000  14.47801         NaN  13.59034
  19    0.0001000000  14.47801  0.13346317  13.59034
  19    0.0002371374  14.47802  0.05506695  13.59034
  19    0.0005623413  14.47801  0.06037268  13.59034
  19    0.0013335214  14.47802  0.11693798  13.59034
  19    0.0031622777  14.47802  0.39541966  13.59034
  19    0.0074989421  14.47802  0.61412118  13.59035
  19    0.0177827941  14.47802  0.70122881  13.59035
  19    0.0421696503  14.47804  0.73065305  13.59037
  19    0.1000000000  14.47806  0.73737851  13.59040

RMSE was used to select the optimal model using the smallest value.
The final values used for the model were size = 1 and decay = 0.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for N/A values</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(training_data<span class="sc">$</span>x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(training_data<span class="sc">$</span>y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="support-vector-machines-svm" class="level2">
<h2 class="anchored" data-anchor-id="support-vector-machines-svm">Support Vector Machines (SVM)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>svm_model <span class="ot">&lt;-</span> <span class="fu">train</span>(training_data<span class="sc">$</span>x,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                  training_data<span class="sc">$</span>y,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"svmRadial"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">preProc =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tuneLength =</span> <span class="dv">10</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>svm_predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_model, <span class="at">newdata =</span> test_data<span class="sc">$</span>x)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>svm_results <span class="ot">&lt;-</span> <span class="fu">postResample</span>(<span class="at">pred =</span> svm_predictions, <span class="at">obs =</span> test_data<span class="sc">$</span>y)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>svm_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Support Vector Machines with Radial Basis Function Kernel 

200 samples
 10 predictor

Pre-processing: centered (10), scaled (10) 
Resampling: Bootstrapped (25 reps) 
Summary of sample sizes: 200, 200, 200, 200, 200, 200, ... 
Resampling results across tuning parameters:

  C       RMSE      Rsquared   MAE     
    0.25  2.635010  0.7685188  2.074977
    0.50  2.423373  0.7839086  1.902162
    1.00  2.284133  0.8001542  1.791776
    2.00  2.196624  0.8126474  1.713560
    4.00  2.143035  0.8209820  1.668024
    8.00  2.119154  0.8246316  1.649386
   16.00  2.117441  0.8248674  1.648573
   32.00  2.117441  0.8248674  1.648573
   64.00  2.117441  0.8248674  1.648573
  128.00  2.117441  0.8248674  1.648573

Tuning parameter 'sigma' was held constant at a value of 0.06299324
RMSE was used to select the optimal model using the smallest value.
The final values used for the model were sigma = 0.06299324 and C = 16.</code></pre>
</div>
</div>
<p>k-Nearest Neighbors (kNN) Results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>knn_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     RMSE  Rsquared       MAE 
3.1750657 0.6785946 2.5443169 </code></pre>
</div>
</div>
<p>Multivariate Adaptive Regression Splines (MARS) Results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mars_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     RMSE  Rsquared       MAE 
1.7901760 0.8705315 1.3712537 </code></pre>
</div>
</div>
<p>Neural Network Results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>neural_network_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    RMSE Rsquared      MAE 
14.27693       NA 13.38691 </code></pre>
</div>
</div>
<p>Support Vector Machines (SVM) Results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>svm_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     RMSE  Rsquared       MAE 
2.0736997 0.8256573 1.5751967 </code></pre>
</div>
</div>
</section>
<section id="mars-model---variable-importance" class="level2">
<h2 class="anchored" data-anchor-id="mars-model---variable-importance">MARS Model - Variable Importance</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImp</span>(mars_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>earth variable importance

   Overall
X1  100.00
X4   82.92
X2   64.47
X5   40.67
X3   28.65
X6    0.00</code></pre>
</div>
</div>
</section>
<section id="model-performance-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-performance-comparison">Model Performance Comparison</h2>
<p>The optimal k for the k-NN model is 15. The optimal nprune for the MARS model is 9. The optimal size is 1, and the optimal decay is 0 for the neural network model. The optimal C is 16, and the optimal σ is 0.063 for the SVM-RBF model. Given the above output results, the MARS model performed best with the highest R-squared of 0.871 and the lowest RMSE of 1.790. Upon inspection of the variable importance for the MARS model, we conclude the most informative predictors to be X1, X4, X2, X5, and X3 (descending order). The X6 predictor is not informative.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>